version: "3.9"
services:
  database:
    container_name: db-peer-evaluation
    image: postgres:17.2-alpine3.19@sha256:d98de4f4959fb6b4531f3fb0cfe92aa49f799e5ebc7a086ae7775b59e7d534e7
    ports:
      - 5555:5432
    env_file: .env
    networks:
      - peer_evaluation

  mailhog:
    image: mailhog/mailhog:v1.0.1@sha256:8d76a3d4ffa32a3661311944007a415332c4bb855657f4f6c57996405c009bea
    container_name: email-peer-evaluation
    ports:
      - 8025:8025
      - 8026:1025
    networks:
      - peer_evaluation
    depends_on:
      - database

networks:
  peer_evaluation:
