version: "3.9"
services:
  database:
    container_name: db-peer-evaluation
    image: postgres:16.3-alpine3.19@sha256:1abbdd8c5bfb10ba18bb39a447e0a6980754f51e2dafb5541988743fb0a01144
    ports:
      - 5432:5432
    env_file: .env
    networks:
      - peer_evaluation

  mailhog:
    image: mailhog/mailhog:v1.0.1@sha256:8d76a3d4ffa32a3661311944007a415332c4bb855657f4f6c57996405c009bea
    container_name: email-peer-evaluation
    ports:
      - 8025:8025
      - 8026:1025
    networks:
      - peer_evaluation
    depends_on:
      - database

networks:
  peer_evaluation:
