version: "3.9"
services:
  database:
    container_name: db_peer_evaluation
    #PostgreSQL 13.5
    image: postgres@sha256:f50997df18443e77e1c6d5b3eb69670e91f57c264202114024a75dcb8ca91ff2
    ports:
      - "5432:5432"
    env_file: .env
  
