version: "3.9"
services:
  database:
    container_name: db-peer-evaluation
    #PostgreSQL 13.5
    image: postgres@sha256:3162a6ead070474b27289f09eac4c865e75f93847a2d7098f718ee5a721637c4
    ports:
      - "5432:5432"
    env_file: .env
    networks:
      - peer_evaluation

  mailhog:
    # MailHog v1.0.1
    image: mailhog/mailhog@sha256:8d76a3d4ffa32a3661311944007a415332c4bb855657f4f6c57996405c009bea
    container_name: email-peer-evaluation
    ports:
      - 8025:8025
      - 1025:1025
    networks:
      - peer_evaluation

networks:
  peer_evaluation:
