version: "3.9"
services:
  database:
    container_name: db-peer-evaluation
    image: postgres:17.0-alpine3.19@sha256:79ac4cc9379deb347f0262b3c97f92e4aff761905b1aef0ab423ebd29ac7d596
    ports:
      - 5432:5432
    env_file: .env
    networks:
      - peer_evaluation

  mailhog:
    image: mailhog/mailhog:v1.0.1@sha256:8d76a3d4ffa32a3661311944007a415332c4bb855657f4f6c57996405c009bea
    container_name: email-peer-evaluation
    ports:
      - 8025:8025
      - 8026:1025
    networks:
      - peer_evaluation
    depends_on:
      - database

networks:
  peer_evaluation:
