version: "3.9"
services:
  database:
    container_name: db-peer-evaluation
    #PostgreSQL 13.5
    image: postgres@sha256:7e30f5b61fccd7fc08ee5d5594bcebac83f1b8c77d05c88bd43fe563ca266a6d
    ports:
      - 5432:5432
    env_file: .env
    networks:
      - peer_evaluation

  mailhog:
    # MailHog v1.0.1
    image: mailhog/mailhog@sha256:8d76a3d4ffa32a3661311944007a415332c4bb855657f4f6c57996405c009bea
    container_name: email-peer-evaluation
    ports:
      - 8025:8025
      - 8026:1025
    networks:
      - peer_evaluation
    depends_on:
      - database

networks:
  peer_evaluation:
