---
name: Test
on:
  push:
    branches:
      - main
      - staging
      - "PEL-**"
    paths-ignore:
      - README.md
      - CHANGELOG.md
      - .gitignore
      - .github/**
  pull_request:
    types: [opened, reopened, edited]

jobs:
  install-dependencies:
    if: "!contains(github.event.head_commit.message, '[skip-ci]')"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.13.2]

    steps:
      - name: Checkout Code üõéÔ∏è
        uses: actions/checkout@v2.4.0
        with:
          persist-credentials: false

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: Cache NPM
        uses: actions/cache@v2
        id: yarn-cache
        with:
          path: |
            ${{ steps.yarn-cache-dir-path.outputs.dir }}
            **/node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install dependencies
        run: |
          yarn install --frozen-lockfile

  tests:
    runs-on: ubuntu-latest
    needs: install-dependencies
    strategy:
      matrix:
        node-version: [16.13.2]

    steps:
      - name: Checkout Code üõéÔ∏è
        uses: actions/checkout@v2.4.0
        with:
          persist-credentials: false

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: Get cached dependencies
        uses: actions/cache@v2
        id: yarn-cache
        with:
          path: |
            ${{ steps.yarn-cache-dir-path.outputs.dir }}
            **/node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Setup test dependencies
        run: |
          cp .env.sample .env
          npx cypress install

      - name: Start docker container
        id: automated-test
        run: |
          docker-compose up -d

      - name: Run E2E tests
        run: |
          yarn prisma:start
          yarn cypress

      - name: Video Cypress
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: videos-cypress
          path: cypress/videos
          retention-days: 7

      - name: Screenshots Cypress
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: screenshots-cypress
          path: cypress/screenshots
          retention-days: 7

      - name: Run jest tests
        run: yarn test:ci

      - name: Upload coverage jest
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: jest-coverage
          path: coverage
          retention-days: 7

      - name: Exit on failure
        if: failure()
        run: |
          echo "Error running test job"
          exit 1
