---
name: Tests
on:
  workflow_call:
    secrets:
      CODACY_PROJECT_TOKEN:
        description: "The key to record the execution to Codacy"
        required: true
      CODECOV_TOKEN:
        description: "The key to record the execution to CodeCov"
        required: true
      CYPRESS_RECORD_KEY:
        description: "The key to record the execution to Cypress Cloud"
        required: true

jobs:
  tests:
    name: Tests Workflow
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout Code üõéÔ∏è
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          cache: "npm"
          cache-dependency-path: |
            package-lock.json
            prisma/schema.prisma

      - name: Install dependencies
        run: npm ci --legacy-peer-deps

      - name: Setup test environmental variables
        run: |
          cp .env.sample .env

      - name: Start docker container
        run: npm run docker:ci

      - name: Build and start web app in the background
        run: npm run build:start:background
        env:
          ENVIRONMENT: ci
          NODE_ENV: ci

      - name: Run linter check
        run: npm run lint:check

      - name: Run prisma db migrations
        run: npm run prisma:deploy

      - name: Run prisma seed
        run: npm run prisma:seed

      - name: Run jest unit tests
        run: npm run test:jest:ci

      - name: Upload coverage jest
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: jest-coverage
          path: coverage
          retention-days: 7

      - name: Install Cypress
        run: npx cypress install

      - name: Setup Cypress
        run: cp cypress.env.test.json cypress.env.json

      - name: Run Cypress component tests
        uses: cypress-io/github-action@v6
        with:
          browser: chrome
          component: true
          install: false
          record: true
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          LIBGL_ALWAYS_SOFTWARE: 1

      - name: Run Cypress E2E tests
        uses: cypress-io/github-action@v6
        with:
          browser: chrome
          headed: true
          install: false
          record: true
          wait-on: http://localhost:3000
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          LIBGL_ALWAYS_SOFTWARE: 1

      - name: Video Cypress
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: videos-cypress
          path: cypress/videos
          retention-days: 7

      - name: Screenshots Cypress
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: screenshots-cypress
          path: cypress/screenshots
          retention-days: 7

      - name: Run coverage check
        run: npm run test:coverage:check

      - name: Coverage
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: merged-coverage
          path: coverage/merged
          retention-days: 7

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5.4.2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: quizslides/peer-evaluation-lsbu

      - name: Upload coverage reports to Codacy
        run: bash <(curl -Ls https://coverage.codacy.com/get.sh)
        env:
          CODACY_PROJECT_TOKEN: ${{ secrets.CODACY_PROJECT_TOKEN }}

      - name: Exit on failure
        if: failure()
        run: |
          echo "Error running tests job"
          exit 1
