---
name: Tests
on:
  workflow_call:

jobs:
  tests:
    name: Tests Workflow
    runs-on: ubuntu-latest
    timeout-minutes: 30
    strategy:
      matrix:
        node-version: [16.13.2]

    steps:
      - name: Checkout Code üõéÔ∏è
        uses: actions/checkout@v2.4.0
        with:
          persist-credentials: false

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: Get cached dependencies
        uses: actions/cache@v2
        id: yarn-cache
        with:
          path: |
            ${{ steps.yarn-cache-dir-path.outputs.dir }}
            **/node_modules
          # yamllint disable-line
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}-${{ hashFiles('**/schema.prisma') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Setup test environmental variables
        run: |
          cp .env.sample .env

      - name: Start docker container
        run: yarn docker:ci

      - name: Build and start web app in the background
        run: yarn build:start:background
        env:
          ENVIRONMENT: ci
          NODE_ENV: ci

      - name: Run linter check
        run: yarn lint:check

      - name: Run prisma db migrations
        run: yarn prisma:deploy

      - name: Run prisma seed
        run: yarn prisma:seed

      - name: Run jest unit tests
        run: yarn test:jest:ci

      - name: Upload coverage jest
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: jest-coverage
          path: coverage
          retention-days: 7

      - name: Install Cypress
        run: npx cypress install

      - name: Setup Cypress
        run: cp cypress.env.test.json cypress.env.json

      - name: Run Cypress component tests
        uses: cypress-io/github-action@v5
        with:
          install: false
          component: true
          browser: chrome
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Run Cypress E2E tests
        uses: cypress-io/github-action@v5
        with:
          install: false
          browser: chrome
          headed: true
          wait-on: http://localhost:3000
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Video Cypress
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: videos-cypress
          path: cypress/videos
          retention-days: 7

      - name: Screenshots Cypress
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: screenshots-cypress
          path: cypress/screenshots
          retention-days: 7

      - name: Run coverage check
        run: yarn test:coverage:check

      - name: Coverage
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: merged-coverage
          path: coverage/merged
          retention-days: 7

      - name: Exit on failure
        if: failure()
        run: |
          echo "Error running tests job"
          exit 1
